name: Trigger Workflow

on:
   workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

  #  steps:
   #   - name: Trigger another workflow
    #    run: |
     #     curl -X POST \
      #      -H "Authorization: token ${{ secrets.TOKEN }}" \
       #     -H "Accept: application/vnd.github.v3+json" \
        #    https://api.github.com/repos/Stackmeisterei/elden-test-repo/actions/workflows/test.yml/dispatches \
         #   -d '{"ref":"refs/heads/main"}'
