name: Trigger Workflow

on:
   workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Logic App for all tags
      run: |
        for tag in dev prod latest; do
        curl -X POST https://<your_logic_app_url> \
          -H "Content-Type: application/json" \
          -d '{
            "tag": "'"$tag"'",
            "image": "ghcr.io/orgA/myapp:'"$tag"'",
            "sha": "'"${{ github.sha }}"'"
          }'
        done
