name: Trigger Workflow

on:
   workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Logic App for dev tags
      run: |
        curl -X POST https://prod-142.westeurope.logic.azure.com:443/workflows/8a3f012c401641d3b2b5a6d257872eea/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=UkfQ9ylWjHhQGHHPYFtCrzfG34b3buZInrJnQ05BbjM\
          -H "Content-Type: application/json" \
          -d '{
            "tag": "prod",
            "image": "ghcr.io/eldensokoli/test-project:prod",
            "sha": "'"${{ github.sha }}"'"
          }'
        done
